name: deploy to test

env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  OUTPUT_LOCATION: "dist" # location of client code build output
on:
  workflow_run:
    workflows: ["Build-CI"]
    types:
      - completed
  
permissions:
  issues: write
  contents: read
jobs:
  deploy:
    environment:
      name: testing
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: actions/download-artifact@v3
       with:
          name: my-artifact
          path: ./artifacts
          
     - name: deploy
       uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
       with:
        skip_app_build: true
        azure_static_web_apps_api_token: e2100d71d8679ce534ef29252ca778b35333024f748a7f39935d648deb6f3a453-38315127-8f6b-48e5-8328-ca891d3d105700075980
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
