name: Deploy-CD

env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  OUTPUT_LOCATION: "dist" # location of client code build output
on:
  workflow_run:
    workflows: ["Build-CI"]
    types:
      - completed
  
permissions:
  id-token: write
  issues: write
  contents: read
  pull-requests: write
jobs:
  deploy-to-testing:
    name: Deploy to testing
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: testing
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: dawidd6/action-download-artifact@v2
       with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
          
     - name: deploy
       uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
       with:
        skip_app_build: true
        azure_static_web_apps_api_token: e2100d71d8679ce534ef29252ca778b35333024f748a7f39935d648deb6f3a453-38315127-8f6b-48e5-8328-ca891d3d105700075980
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
            
  notify-testing:
    name: notify testing deployed
    runs-on: ubuntu-latest 
    needs: deploy-to-testing 
    steps:
      - name: Download Variable Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: variable-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}

      - name: Read Variable from File
        run: |
          variable_value=$(cat variable-artifact/variable.txt)
          echo "Variable Value: $variable_value"
          echo "pr_number=$variable_value" >> $GITHUB_ENV
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const pr_number = process.env.pr_number;
            console.log('PR number is: $pr_number');
            if (pr_number) {
                const commentBody = "Workflow ${{ github.workflow }} (${{ github.sha }}) has completed and deployed to testing with status ${{ job.status }}";
                await github.rest.issues.createComment({
                          issue_number: pr_number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,                          
                          body: commentBody,
                      });
                      }                      
            
  deploy-to-staging:
    name: Deploy to staging
    needs: deploy-to-testing
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
         skip_app_build: true
         azure_static_web_apps_api_token: 8376de50796f1fa63a9262bb916dc2358eb55be4544594013a981a6daab797ae3-73c428c3-4425-466f-a984-a953c97dbcc100075981 
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         action: "upload"
         app_location: ${{ env.APP_LOCATION }}
         api_location: ${{ env.API_LOCATION }}
         output_location: ${{ env.OUTPUT_LOCATION }}

  notify-staging:
    name: notify staging deployed
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    steps:
      - run: |
         curl 
          -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/younis318/hello-world/issues/${{ github.event.pull_request.number }}/comments \
          -d '{"body":"Workflow ${{ github.workflow }} (${{ github.sha }}) has completed and deployed to staging with status ${{ job.status }}"}'

  deploy-to-production:
     name: Deploy to production
     needs: deploy-to-staging
     environment:
       name: production
     runs-on: ubuntu-latest
     steps:
        - name: Download artifacts
          uses: dawidd6/action-download-artifact@v2
          with:
            name: my-artifact
            workflow: ${{ github.event.workflow_run.workflow_id }}
        - name: deploy
          uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
          with:
           skip_app_build: true
           azure_static_web_apps_api_token: 9d2c15df1c6ee843255d95a7eaa549370aed3510dc0b717c60b9e191bc24f5253-350a4aa8-06ed-4a2b-9286-f2c43d4e953d00075982
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           action: "upload"
           app_location: ${{ env.APP_LOCATION }}
           api_location: ${{ env.API_LOCATION }}
           output_location: ${{ env.OUTPUT_LOCATION }}
  notify-production:
    name: notify production deployed
    runs-on: ubuntu-latest
    needs: deploy-to-production
    steps:
      - run: |
         curl 
          -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/younis318/hello-world/issues/${{ github.event.pull_request.number }}/comments \
          -d '{"body":"Workflow ${{ github.workflow }} (${{ github.sha }}) has completed and deployed to production with status ${{ job.status }}"}'
