name: Deploy-CD

env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  OUTPUT_LOCATION: "dist" # location of client code build output
on:
  workflow_run:
    workflows: ["Build-CI"]
    types:
      - completed
  
permissions:
  issues: write
  contents: read
jobs:
  deploy-to-testing:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: testing
    runs-on: ubuntu-latest
    steps:
     - name: Download artifacts
       uses: dawidd6/action-download-artifact@v2
       with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
          
     - name: deploy
       uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
       with:
        skip_app_build: true
        azure_static_web_apps_api_token: e2100d71d8679ce534ef29252ca778b35333024f748a7f39935d648deb6f3a453-38315127-8f6b-48e5-8328-ca891d3d105700075980
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
  deploy-to-staging:
    name: Deploy to staging
    needs: deploy-to-testing
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          name: my-artifact
          workflow: ${{ github.event.workflow_run.workflow_id }}
      - name: deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
         skip_app_build: true
         azure_static_web_apps_api_token: 8376de50796f1fa63a9262bb916dc2358eb55be4544594013a981a6daab797ae3-73c428c3-4425-466f-a984-a953c97dbcc100075981 
         repo_token: ${{ secrets.GITHUB_TOKEN }}
         action: "upload"
         app_location: ${{ env.APP_LOCATION }}
         api_location: ${{ env.API_LOCATION }}
         output_location: ${{ env.OUTPUT_LOCATION }}

  deploy-to-production:
     name: Deploy to production
     needs: deploy-to-staging
     environment:
       name: production
     runs-on: ubuntu-latest
     steps:
        - name: Download artifacts
          uses: dawidd6/action-download-artifact@v2
          with:
            name: my-artifact
            workflow: ${{ github.event.workflow_run.workflow_id }}
        - name: deploy
          uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
          with:
           skip_app_build: true
           azure_static_web_apps_api_token: 9d2c15df1c6ee843255d95a7eaa549370aed3510dc0b717c60b9e191bc24f5253-350a4aa8-06ed-4a2b-9286-f2c43d4e953d00075982
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           action: "upload"
           app_location: ${{ env.APP_LOCATION }}
           api_location: ${{ env.API_LOCATION }}
           output_location: ${{ env.OUTPUT_LOCATION }}
